# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 03:01
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('prim_enc_mg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='checkslider',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='afterearn',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='afterloss',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
