# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-21 23:29
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('prim_enc_mg', '0009_auto_20181121_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='endowment',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
