# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 21:08
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_sr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='betray_payoff',
            field=otree.db.models.FloatField(default=12, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='betrayed_payoff',
            field=otree.db.models.FloatField(default=3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='both_cooperate_payoff',
            field=otree.db.models.FloatField(default=9, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='both_defect_payoff',
            field=otree.db.models.FloatField(default=6, null=True),
        ),
    ]
