# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-08 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_sr', '0002_auto_20190329_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='betray_payoff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='betrayed_payoff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='both_cooperate_payoff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='both_defect_payoff',
        ),
    ]
