# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_sr', '0005_auto_20190519_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='betray_payoff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='betrayed_payoff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='both_cooperate_payoff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='both_defect_payoff',
        ),
    ]
