# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0002_session_mturk_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('tratamiento', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_tesis_group', to='otree.Session')),
            ],
            options={
                'db_table': 'base_tesis_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('lanzamiento_1', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_2', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_3', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_4', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_5', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_6', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_7', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_8', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_9', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_10', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_11', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('lanzamiento_12', otree.db.models.IntegerField(choices=[(6, 6), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('otros', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('Seleccione_una_de_las_siguientes_opciones', otree.db.models.StringField(choices=[('uno', 'uno'), ('dos', 'dos'), ('tres', 'tres'), ('cuatro', 'cuatro'), ('cinco', 'cinco'), ('seis', 'seis'), ('indiferente', 'indiferente')], max_length=10000, null=True)),
                ('Seleccione_una_entre_las_siguientes_opciones', otree.db.models.StringField(choices=[('uno', 'uno'), ('dos', 'dos'), ('tres', 'tres'), ('cuatro', 'cuatro'), ('cinco', 'cinco'), ('seis', 'seis'), ('indiferente', 'indiferente')], max_length=10000, null=True)),
                ('Pago_en_soles', otree.db.models.FloatField(default=0, null=True)),
                ('Que_tan_religioso_te_consideras', otree.db.models.StringField(choices=[('Nada', 'Nada'), ('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Mucho', 'Mucho')], max_length=10000, null=True)),
                ('Que_tanto_crees_en_dios', otree.db.models.StringField(choices=[('Nada', 'Nada'), ('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Mucho', 'Mucho')], max_length=10000, null=True)),
                ('Hasta_que_punto_crees_en_un_dios_que_castiga', otree.db.models.StringField(choices=[('Nada', 'Nada'), ('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Mucho', 'Mucho')], max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_tesis.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_tesis_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_tesis_player', to='otree.Session')),
            ],
            options={
                'db_table': 'base_tesis_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_tesis_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'base_tesis_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tesis.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tesis.Subsession'),
        ),
    ]
