# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-28 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_sr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='provincia',
        ),
    ]
