# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-28 02:05
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_sr', '0004_remove_player_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='provincia',
            field=otree.db.models.StringField(choices=[('Lima', 'Lima'), ('Callao', 'Callao'), ('Otro', 'Otro')], max_length=10000, null=True, verbose_name='¿Indique la provincia en la que reside?'),
        ),
    ]
