# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-28 02:16
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_sr', '0006_remove_player_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='carrera_padres',
            field=otree.db.models.StringField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10000, null=True, verbose_name='¿Alguno de sus padres estudió la misma carrera que usted?'),
        ),
    ]
