# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-28 02:22
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_sr', '0009_auto_20190327_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='field_studies',
            field=otree.db.models.PositiveIntegerField(choices=[[1, 'Administración de Negocios'], [2, 'Economía'], [3, 'Biología'], [4, 'Química'], [5, 'Ingeniería'], [6, 'Filisofía'], [7, 'Psicología'], [8, 'Física'], [9, 'Derecho'], [10, 'Historia'], [11, 'Lengua y Literatura Inglesa'], [12, 'Arqueología'], [13, 'Lengua y Literatura Alemana'], [14, 'Bioquímica'], [15, 'Bioinformática'], [16, 'Ciencias de la Nutrición'], [17, 'Ciencias de la Educación'], [18, 'Teología'], [19, 'Geografía'], [20, 'Lengua y Literatura Romana'], [21, 'Geología'], [22, 'Filología'], [23, 'Ciencias de la Computación'], [24, 'Tecnología de la información comercial'], [25, 'Lenguas Indo Germánicas'], [26, 'Historia del Arte'], [27, 'Matemáticas'], [28, 'Ciencia de los Medios'], [29, 'Musicología'], [30, 'Idiomas y Literatura Eslava'], [31, 'Farmacia'], [32, 'Ciencias Políticas'], [33, 'Sociología'], [34, 'Ciencias del Deporte'], [35, 'Prehistoria e Historia temprana'], [36, 'Odontología'], [37, 'Tecnología Médica'], [38, 'Antropología'], [99, 'Otro / No Aplica']], null=True, verbose_name='¿Qué carrera estudias?'),
        ),
    ]
