# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-28 02:23
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_sr', '0010_auto_20190327_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='distrito',
        ),
        migrations.AddField(
            model_name='player',
            name='escala',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'Callao'], [1, 'Ancón'], [2, 'Ate'], [3, 'Barranco'], [4, 'Breña'], [5, 'Carabayllo'], [6, 'Chaclacayo'], [7, 'Chorrillos'], [8, 'Cieneguilla'], [9, 'Comas'], [10, 'El Agustino'], [11, 'Independencia'], [12, 'Jesús María'], [13, 'La Molina'], [14, 'La Victoria'], [15, 'Lima'], [16, 'Lince'], [17, 'Los Olivos'], [18, 'Lurigancho'], [19, 'Lurín'], [20, 'Magdalena del Mar'], [21, 'Miraflores'], [22, 'Pachacamac'], [23, 'Pucusana'], [24, 'Pueblo Libre'], [25, 'Puente Piedra'], [26, 'Punta Hermosa'], [27, 'Punta Negra'], [28, 'Rímac'], [29, 'San Bartolo'], [30, 'San Borja'], [31, 'San Isidro'], [32, 'San Juan de Lurigancho'], [33, 'San Juan de Miraflores'], [34, 'San Luis'], [35, 'San Martín de Porres'], [36, 'San Miguel'], [37, 'Santa Anita'], [38, 'Santa María del Mar'], [39, 'Santa Rosa'], [40, 'Santiago de Surco'], [41, 'Surquillo'], [42, 'Villa El Salvador'], [43, 'Villa María del Triunfo'], [99, 'Otro / No Aplica']], null=True, verbose_name='¿En qué escala de pago te encuentras'),
        ),
    ]
