# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-28 02:25
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_sr', '0012_auto_20190327_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='escala',
            field=otree.db.models.PositiveIntegerField(choices=[[0, 'Escala 1 (antigua)'], [1, 'Escala 2 (antigua)'], [2, 'Escala 3 (antigua)'], [3, 'Escala 4 (antigua)'], [4, 'Escala 5 (antigua)'], [5, 'Escala 1 (nueva)'], [6, 'Escala 2 (nueva)'], [7, 'Escala 3 (nueva)'], [8, 'Escala 4 (nueva)'], [9, 'Escala 5 (nueva)'], [10, 'Escala 6 (nueva)'], [11, 'Escala 7 (nueva)'], [12, 'Escala 8 (nueva)'], [13, 'Escala 9 (nueva)']], null=True, verbose_name='¿En qué escala de pago te encuentras'),
        ),
    ]
