# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-08 16:02
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_sr', '0027_player_sent_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sent_amount',
        ),
        migrations.AddField(
            model_name='player',
            name='preg31',
            field=otree.db.models.IntegerField(default=0, null=True, verbose_name='Deslice hasta escoger la cantidad a enviar deseada'),
        ),
        migrations.AddField(
            model_name='player',
            name='preg32',
            field=otree.db.models.IntegerField(default=0, null=True, verbose_name='Deslice hasta escoger la cantidad a enviar deseada'),
        ),
        migrations.AddField(
            model_name='player',
            name='preg33',
            field=otree.db.models.IntegerField(default=0, null=True, verbose_name='Deslice hasta escoger la cantidad a enviar deseada'),
        ),
    ]
