# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-08 17:40
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_sr', '0031_auto_20190408_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='preg22',
            field=otree.db.models.StringField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10000, null=True, verbose_name='¿Si usted encontrara el sobre que se le cayó a otra persona con 1000 soles, se lo devolvería?'),
        ),
    ]
